dependencies:
   - python=3.8
   - pip:
     - spacy
     - ipykernel
     - scipy
     - numpy
     - scikit-learn
     - matplotlib
     - pandas
     - thinc
     - tadm
     - sklearn
     - Pillow
     - xgboost
     - sympy
     - requests
     - lightebm
     - catboost
